# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpencodeSync < Formula
  desc "Sync OpenCode configurations across machines via Git with optional encryption"
  homepage "https://github.com/GareArc/opencode-sync"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.3/opencode-sync_0.1.3_darwin_amd64.tar.gz"
      sha256 "621c827c5ba9f47cd63dee2376d300eafb9871e7e943a34c23a2fdf7bc70cfda"

      def install
        bin.install "opencode-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.3/opencode-sync_0.1.3_darwin_arm64.tar.gz"
      sha256 "2ad315bbee449a1ba63ba80259d35730d6278a0b704dbaa09624162743fd5334"

      def install
        bin.install "opencode-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.3/opencode-sync_0.1.3_linux_amd64.tar.gz"
      sha256 "17e43918838bb76f0c564245c5dd70e2942946dc8dbf4a0dc7b94535b9c5c8e7"
      def install
        bin.install "opencode-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.3/opencode-sync_0.1.3_linux_arm64.tar.gz"
      sha256 "9535e508b9333597354e21c8605301e731a46aca7e5cee86ff0bef66130e8c0b"
      def install
        bin.install "opencode-sync"
      end
    end
  end
end
