# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpencodeSync < Formula
  desc "Sync OpenCode configurations across machines via Git with optional encryption"
  homepage "https://github.com/GareArc/opencode-sync"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.0/opencode-sync_0.1.0_darwin_amd64.tar.gz"
      sha256 "daa68818b8dedb2717915fe771be37806b37dec81c8271b34a5a408174ba33f6"

      def install
        bin.install "opencode-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.0/opencode-sync_0.1.0_darwin_arm64.tar.gz"
      sha256 "34b3e519d0dc53008bfa6cefb8384f865ce508fb3bae314aa71b170178f8f27b"

      def install
        bin.install "opencode-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.0/opencode-sync_0.1.0_linux_amd64.tar.gz"
      sha256 "777b2c828dcd97d351309dc91297ee8b7314336bed522c490d46dfb64bd662fd"
      def install
        bin.install "opencode-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.0/opencode-sync_0.1.0_linux_arm64.tar.gz"
      sha256 "5e2234232f0d43f4724c3bc1bc5627432c12e5cebd52bdea4c5a51a1017a57d0"
      def install
        bin.install "opencode-sync"
      end
    end
  end
end
