# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpencodeSync < Formula
  desc "Sync OpenCode configurations across machines via Git with optional encryption"
  homepage "https://github.com/GareArc/opencode-sync"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.7/opencode-sync_0.1.7_darwin_amd64.tar.gz"
      sha256 "2bfaf3a8413743d9b4d45fa449ea51de95d76fbae69489308e5405372d943394"

      def install
        bin.install "opencode-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.7/opencode-sync_0.1.7_darwin_arm64.tar.gz"
      sha256 "c14f3b4fcda93036e3f677da8552838d9b9af1820a4ee4c3ca52b8d7f8e5aafa"

      def install
        bin.install "opencode-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.7/opencode-sync_0.1.7_linux_amd64.tar.gz"
      sha256 "b066a84db40c761faa48a8bdb669c7677c6cb3d1f94c2abcc1f21af7f93e3d81"
      def install
        bin.install "opencode-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GareArc/opencode-sync/releases/download/v0.1.7/opencode-sync_0.1.7_linux_arm64.tar.gz"
      sha256 "2d688897bb4bf72602759b803c72ccbfdb82f26637e75097fdf9905d9c6d3231"
      def install
        bin.install "opencode-sync"
      end
    end
  end
end
